---
backend:
  name: git-gateway
  branch: main

logo_url: https://saetta-labs.netlify.app/images/saetta-logo.svg

show_preview_links: false
search: false

media_folder: "src/images/cms/" # Media files will be stored in the repo under src/images/
public_folder: "/images/cms/" # The src attribute for uploaded media will begin with /images/

collections:
  - name: global
    label: Settings
    files:
      - label: Site Meta
        name: meta
        editor:
          preview: false
        file: src/_data/meta.json
        fields:
          - label: SEO Title
            name: seo_title
            widget: string
            required: true
          - label: SEO Description
            name: seo_description
            widget: text
            required: true
          - label: Social Share Image
            name: og_img
            widget: image
            media_folder: /src/images/cms/og/
            public_folder: /images/cms/og/
            allow_multiple: false
            choose_url: false
            hint: Preview image shown in social media shares

  - name: pages
    label: Pages
    files:
      - label: Homepage
        name: homepage
        editor:
          preview: false
        file: src/homepage.md
        fields:
          - label: Hero Image
            name: hero_image
            widget: image
            media_folder: /src/images/cms/home/
            public_folder: /images/cms/home/
            allow_multiple: false
            choose_url: false
          - label: Hero Heading
            name: hero_heading
            widget: string
            required: true
          - label: Hero Subheading
            name: hero_subheading
            widget: string
            required: true
          - label: Plugs
            label_singular: Plug
            name: plugs
            widget: list
            collapsed: true
            minimize_collapsed: false
            allow_add: true
            add_to_top: true
            summary: "{{fields.title}}"
            fields:
              - label: Title
                name: title
                widget: string
              - label: Blurb
                name: blurb
                widget: markdown
                minimal: true
                buttons: [bold, italic]
                modes: [rich_text]
                editor_components: []
                required: true
              - label: Teaser Image
                name: teaser
                widget: image
                media_folder: /src/images/cms/home/
                public_folder: /images/cms/home/
                allow_multiple: false
                choose_url: false
              - label: Link
                name: link
                widget: string
              - label: Link Text
                name: link_text
                widget: string
                required: false
          - label: About the Company
            name: about_blurb
            widget: markdown
            editor_components: []
            buttons:
              [
                bold,
                italic,
                link,
                heading-two,
                heading-three,
                heading-four,
                heading-five,
                heading-six,
                bulleted-list,
                numbered-list,
              ]
            modes: [rich_text]
            required: true

      - label: Products
        name: products
        editor:
          preview: false
        file: src/products.md
        fields:
          - label: Page Title
            name: seo_title
            widget: string
            required: true
          - label: Products
            label_singular: Product
            name: products
            widget: list
            collapsed: true
            minimize_collapsed: false
            allow_add: false
            summary: "{{title}}"
            fields:
              - { label: Product Title, name: title, widget: string }
              - {
                  label: Description,
                  name: description,
                  widget: markdown,
                  minimal: true,
                  editor_components: [],
                  buttons: [bold, italic, link],
                  modes: [rich_text],
                  required: true,
                }
              - label: Photo
                name: photo
                widget: image
                media_folder: /src/images/cms/products/
                public_folder: /images/cms/products/
                allow_multiple: false
                choose_url: false
              - label: Datasheet
                name: datasheet
                widget: file
                allow_multiple: false
                choose_url: false
                media_folder: /src/pdfs/
                required: false
              - label: Plot Image
                name: plot_image
                widget: image
                media_folder: /src/images/cms/products/
                public_folder: /images/cms/products/
                allow_multiple: false
                choose_url: false
              - {
                  label: Plot Description,
                  name: plot_description,
                  widget: markdown,
                  minimal: true,
                  buttons: [bold, italic, link],
                  modes: [rich_text],
                  editor_components: [],
                  required: true,
                }

      - label: Lab
        name: lab
        editor:
          preview: false
        file: src/pages/lab.md
        fields:
          - label: Page Title
            name: seo_title
            widget: string
            required: true

      - label: About
        name: about
        editor:
          preview: false
        file: src/pages/about.md
        fields:
          - label: Page Title
            name: seo_title
            widget: string
            required: true
          - label: Body
            name: body
            widget: markdown
            editor_components: []
            buttons:
              [
                bold,
                italic,
                link,
                heading-two,
                heading-three,
                heading-four,
                heading-five,
                heading-six,
                bulleted-list,
                numbered-list,
              ]
            modes: [rich_text]
            required: true

      - label: Contact
        name: contact
        editor:
          preview: false
        file: src/pages/contact.md
        fields:
          - label: Page Title
            name: seo_title
            widget: string
            required: true
          - label: Body
            name: body
            widget: markdown
            editor_components: []
            buttons: [bold, italic, link]
            modes: [rich_text]
            required: true

      - label: Thank You
        name: thanks
        editor:
          preview: false
        file: src/pages/excluded/thanks.md
        fields:
          - label: Page Title
            name: seo_title
            widget: string
            required: true
          - label: Body
            name: body
            widget: markdown
            editor_components: []
            buttons: [bold, italic, link]
            modes: [rich_text]
            required: true

      - label: Page Not Found (404 Error)
        name: error404
        editor:
          preview: false
        file: src/pages/excluded/404.md
        fields:
          - label: Page Title
            name: seo_title
            widget: string
            required: true
          - label: Body
            name: body
            widget: markdown
            editor_components: []
            buttons: [bold, italic, link]
            modes: [rich_text]
            required: true

  - name: posts
    label: Lab Posts
    label_singular: Post
    folder: src/posts/
    slug: "{{fields.publish_date}}-{{slug}}"
    extension: md
    create: true # Allow users to create new documents in this collection
    delete: true # Allow users to delete items in this collection
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - label: Title
        name: title
        widget: string
      - label: Teaser Image
        name: teaser
        widget: image
        media_folder: /src/images/cms/posts/
        public_folder: /images/cms/posts/
        allow_multiple: false
        choose_url: false
      - label: Link
        name: link
        widget: string
      - label: Link Text
        name: link_text
        widget: string
        required: false
      - label: Show on Homepage?
        name: homepage
        widget: boolean
        required: false
      - label: Body
        name: body
        widget: markdown
        minimal: true
        modes: [rich_text]
        editor_components: []
        buttons: [bold, italic]
        required: true
