---
backend:
  name: git-gateway
  branch: main

show_preview_links: false

media_folder: "src/images/" # Media files will be stored in the repo under src/images/
public_folder: "/images/" # The src attribute for uploaded media will begin with /images/

collections:
  - name: global
    label: Settings
    files:
      - label: Site Meta
        name: meta
        editor:
          preview: false
        file: src/_data/meta.json
        fields:
          - label: SEO Title
            name: seo_title
            widget: string
            required: true
          - label: SEO Description
            name: seo_description
            widget: text
            required: true
          - label: Social Share Image
            name: og_img
            widget: image
            allow_multiple: false
            choose_url: false
            hint: Preview image shown in social media shares

  - name: pages
    label: Pages
    files:
      - label: Homepage
        name: homepage
        editor:
          preview: false
        file: src/homepage.md
        fields:
          - label: Hero Image
            name: hero_image
            widget: image
            allow_multiple: false
            choose_url: false
          - label: Hero Heading
            name: hero_heading
            widget: string
            required: true
          - label: Hero Subheading
            name: hero_subheading
            widget: string
            required: true
          - label: About the Company
            name: about_blurb
            widget: markdown
            editor_components: []
            modes: [rich_text]
            required: true

      - label: Products
        name: products
        editor:
          preview: false
        file: src/products.md
        fields:
          - label: Page Title
            name: page_heading
            widget: string
            required: true
          - label: Products
            label_singular: Product
            name: products
            widget: list
            collapsed: true
            minimize_collapsed: false
            allow_add: true
            add_to_top: true
            summary: "{{title}}"
            fields:
              - { label: Product Title, name: title, widget: string }
              - {
                  label: Description,
                  name: description,
                  widget: markdown,
                  minimal: true,
                  buttons: [bold, italic, link],
                  modes: [rich_text],
                  editor_components: [],
                  required: true,
                }
              - label: Photo
                name: photo
                widget: image
                allow_multiple: false
                choose_url: false
              - label: Datasheet
                name: datasheet
                widget: file
                allow_multiple: false
                choose_url: false
                media_folder: pdfs/
                required: false

      - label: Library
        name: library
        editor:
          preview: false
        file: src/pages/library.md
        fields:
          - label: Page Title
            name: page_heading
            widget: string
            required: true
          - label: Body
            name: body
            widget: markdown
            editor_components: []
            modes: [rich_text]
            required: true

      - label: About
        name: about
        editor:
          preview: false
        file: src/pages/about.md
        fields:
          - label: Page Title
            name: page_heading
            widget: string
            required: true
          - label: Body
            name: body
            widget: markdown
            editor_components: []
            modes: [rich_text]
            required: true

      - label: Contact
        name: contact
        editor:
          preview: false
        file: src/pages/contact.md
        fields:
          - label: Page Title
            name: page_heading
            widget: string
            required: true
          - label: Body
            name: body
            widget: markdown
            editor_components: []
            modes: [rich_text]
            required: true

      - label: Thank You
        name: thanks
        editor:
          preview: false
        file: src/pages/excluded/thanks.md
        fields:
          - label: Page Title
            name: page_heading
            widget: string
            required: true
          - label: Body
            name: body
            widget: markdown
            editor_components: []
            modes: [rich_text]
            required: true

      - label: Page Not Found (404 Error)
        name: error404
        editor:
          preview: false
        file: src/pages/excluded/404.md
        fields:
          - label: Page Title
            name: page_heading
            widget: string
            required: true
          - label: Body
            name: body
            widget: markdown
            editor_components: []
            modes: [rich_text]
            required: true
