---
backend:
  name: git-gateway
  branch: main

show_preview_links: false

media_folder: "src/images/" # Media files will be stored in the repo under static/images/
public_folder: "/images/" # The src attribute for uploaded media will begin with /images/

collections:
  - name: pages
    label: Special Pages
    files:
      - label: Homepage
        name: homepage
        delete: true
        editor:
          preview: false
        file: src/_data/homepage.json
        fields:
          - label: Page Title
            name: page_heading
            widget: string
            required: true
          - label: Page Subheading
            name: page_subheading
            widget: string
            required: true

      - label: Products
        name: productspage
        delete: true
        editor:
          preview: false
        file: src/_data/productspage.json
        fields:
          - label: Page Title
            name: page_heading
            widget: string
            required: true
          - label: Products
            label_singular: Product
            name: products
            widget: list
            collapsed: false
            minimize_collapsed: true
            allow_add: true
            add_to_top: true
            summary: "{{title}}"
            fields:
              - { label: Product Title, name: title, widget: string }
              - {
                  label: Description,
                  name: description,
                  widget: markdown,
                  minimal: true,
                  buttons: [bold, italic, link],
                  modes: [rich_text],
                  editor_components: [],
                  required: true,
                }

      - label: Contact
        name: contact
        delete: true
        editor:
          preview: false
        file: src/_data/contactpage.json
        fields:
          - label: Page Title
            name: page_heading
            widget: string
            required: true
          - label: Blurb
            name: blurb
            widget: string
            required: true

  - name: pages_generic
    label: Generic Pages
    label_singular: Generic Page
    folder: src/pages_generic/
    slug: ""
    extension: md
    create: false # Allow users to create new documents in this collection
    delete: false # Allow users to delete items in this collection
    editor:
      preview: false
    summary: "{{cms_title}}"
    fields: # The fields for each document, usually in front matter
      - label: Title
        name: title
        widget: string
      - label: CMS Title
        name: cms_title
        widget: hidden
      - label: Description
        name: body
        widget: markdown
        editor_components: []
        modes: [rich_text]
        required: true
    sortable_fields: ["commit_date", "title"]
