---
backend:
  name: git-gateway
  branch: main

show_preview_links: false

media_folder: "src/images/" # Media files will be stored in the repo under static/images/
public_folder: "/images/" # The src attribute for uploaded media will begin with /images/

collections:
  - name: pages
    label: Pages
    files:
      - label: Homepage
        name: homepage
        delete: true
        editor:
          preview: false
        file: src/homepage.md
        fields:
          - label: Page Title
            name: page_heading
            widget: string
            required: true
          - label: Page Subheading
            name: page_subheading
            widget: string
            required: true

      - label: Products
        name: products
        delete: true
        editor:
          preview: false
        file: src/products.md
        fields:
          - label: Page Title
            name: page_heading
            widget: string
            required: true
          - label: Products
            label_singular: Product
            name: products
            widget: list
            collapsed: true
            minimize_collapsed: false
            allow_add: true
            add_to_top: true
            summary: "{{title}}"
            fields:
              - { label: Product Title, name: title, widget: string }
              - {
                  label: Description,
                  name: description,
                  widget: markdown,
                  minimal: true,
                  buttons: [bold, italic, link],
                  modes: [rich_text],
                  editor_components: [],
                  required: true,
                }

      - label: Library
        name: library
        delete: true
        editor:
          preview: false
        file: src/pages/library.md
        fields:
          - label: Page Title
            name: page_heading
            widget: string
            required: true
          - label: Body
            name: body
            widget: markdown
            editor_components: []
            modes: [rich_text]
            required: true

      - label: About
        name: about
        delete: true
        editor:
          preview: false
        file: src/pages/about.md
        fields:
          - label: Page Title
            name: page_heading
            widget: string
            required: true
          - label: Body
            name: body
            widget: markdown
            editor_components: []
            modes: [rich_text]
            required: true

      - label: Contact
        name: contact
        delete: true
        editor:
          preview: false
        file: src/pages/contact.md
        fields:
          - label: Page Title
            name: page_heading
            widget: string
            required: true
          - label: Body
            name: body
            widget: markdown
            editor_components: []
            modes: [rich_text]
            required: true

      - label: Thank You
        name: thanks
        delete: true
        editor:
          preview: false
        file: src/pages/excluded/thanks.md
        fields:
          - label: Page Title
            name: page_heading
            widget: string
            required: true
          - label: Body
            name: body
            widget: markdown
            editor_components: []
            modes: [rich_text]
            required: true

      - label: Page Not Found (404 Error)
        name: error404
        delete: true
        editor:
          preview: false
        file: src/pages/excluded/404.md
        fields:
          - label: Page Title
            name: page_heading
            widget: string
            required: true
          - label: Body
            name: body
            widget: markdown
            editor_components: []
            modes: [rich_text]
            required: true
